

spring:
  application:
    name: gateway-service

  cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          prefer-ip-address: true
          enabled: true
          register: true
      gateway:
         discovery:
           locator:
             lowerCaseServiceId: true
             enabled: true
         routes:
          - id: spring-boot-service
            uri: lb://spring-boot-service
            predicates:
            - Path=/kbapi/user/**
            filters:
            - StripPrefix=1
server:
  port: 8080


