server:
  port: 8081


spring:
    application:
      name: bmsoft-rbac
    datasource:
      url: jdbc:mysql://localhost:3306/rbac
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
    thymeleaf:
       cache: false
       mode: LEGACYHTML5
