

server:
  port: 8081
  servlet:
    context-path: /

 
spring:
  application:
    name: download
  servlet:
    multipart:
      enabled: true
      max-file-size: 300000MB # 设置单个文件的最大长度
      max-request-size: 500000MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /attach  # 上传的临时目录



