
server:
  port: 8082
  address: 0.0.0.0

sensitive:
     pattern: "\\*{15}"


system:
   source: 01:新采编,02:数据平台,03:新供稿,04:新华社客户端,05:新华国际客户端,06:亚太卫星,07:非洲卫星,08:新华社发布客户端,09:新华网通稿,10:新采编图片,11:高清,12:ENEWS系统,13:移动报道